### ISSUE TITLE
Small issue with an iterator

### ISSUE THREAD

**Issue by TheLounger** [Zhentar/ILSpy#4]
Wrote a small script recently and noticed ILSpy wouldn't decompile it properly.

**Expected output:**
```
public class WaitAndQuit : MonoBehaviour
{
    private void LateUpdate()
    {
        base.StartCoroutine(this.LeaveWaitAndQuit());
    }

    private IEnumerator LeaveWaitAndQuit()
    {
        World.Instance.LeaveWorld(string.Empty);
        AudioController.Play("GeneralQuit");
        yield return new WaitForSeconds(0.75f);
        Application.Quit();
    }
}
```

**Actual output:**
```
public class WaitAndQuit : MonoBehaviour
{
	private void LateUpdate()
	{
		base.StartCoroutine(this.LeaveWaitAndQuit());
	}

	private IEnumerator LeaveWaitAndQuit()
	{
		WaitAndQuit.<LeaveWaitAndQuit>d__0 <LeaveWaitAndQuit>d__ = new WaitAndQuit.<LeaveWaitAndQuit>d__0(0);
		<LeaveWaitAndQuit>d__.<>4__this = this;
		return <LeaveWaitAndQuit>d__;
	}
}
```

**Comment by FonzieMcCloud** [comment]
Same issue here. Any suggestions?

**Comment by TheLounger** [comment]
You're better off using [dnSpy](https://github.com/0xd4d/dnSpy).
This was able to decompile everything from Unity I threw at it.

**Comment by FonzieMcCloud** [comment]
Also ienumerators? I already tried that and its really great. But always throws out "garbage" for ienums. Am i missing a settings or a toggle somewehere?

**Comment by TheLounger** [comment]
Well yes, I thought we were talking about those.
It does have an option for it under Decompiler -> C#, but I think that was enabled by default for me.

**Comment by FonzieMcCloud** [comment]
Yeah, right. I have "decompile enumerators" ticked on. But still i get something like posted in the first post.

Anyway. Dont wanna annoy you any longer with questions about an other product :)

**Comment by TheLounger** [comment]
You can add me on Steam (see my profile) if you want to discuss this further

**Comment by Zhentar** [comment]
If you've compiled with Visual Studio/MSBuild (i.e. the MS compiler rather than the Mono compiler), then this is the expected behavior - the Mono iterator handling replaces the MS version and I haven't wanted to figure out how to differentiate the two. If that is not the case, then what Unity version are you using?
