### ISSUE TITLE
Decompile Exception on rimworld a16 class

### ISSUE THREAD

**Issue by erdelf** [Zhentar/ILSpy#5]
This ILSpy version returns a decompiler exception (following) for the a16 unstable branch of rimworld on `Verse.BackstoryTranslationUtility` while the ilspy.net version works fine

`ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Collections.Generic.IEnumerable<System.Xml.Linq.XElement> Verse.BackstoryTranslationUtility::BackstoryTranslationElements(Verse.LoadedLanguage)
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.`

**Comment by Zhentar** [comment]
It looks like this issue is the same one that I fixed in 1.0.1, could you give that a try?

**Comment by erdelf** [comment]
had to reload and it takes a bit longer than for other classes. but apparently it works fine, sry for bothering then, I somehow missed the new release.
